version: "2"
services:
  openvpn:
    image: kylemanna/openvpn
    networks:
      - openvpn
    cap_add:
      - NET_ADMIN
    ports:
    - 1194:1194/tcp
    - 8081:8081/tcp
    volumes:
    - ./.tmp/ovpn-config:/etc/openvpn

networks:
  openvpn:
